// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egrohrtaazpahdwsvzsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncm9ocnRhYXpwYWhkd3N2enN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc0NjcsImV4cCI6MjA2OTkxMzQ2N30.fLZ8kPhY2aRCuG6lQSAy5Niyt5YR87RxJVgW8CeZ4Ks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});